In [ ]:
##  2a: deep forward network with two hidden layers to perform multiclass classification and predicting the class

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.datasets import make_classification
# Step 1: Generate or load data
# Here, we create a synthetic dataset for multiclass classification
X, y = make_classification(
    n_samples=1000,        # Number of samples
    n_features=20,         # Number of features
    n_informative=15,      # Number of informative features
    n_classes=3,           # Number of classes
    random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler
# Step 2: Preprocess the data
# Scale the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
from tensorflow.keras.utils import to_categorical
# Convert labels to one-hot encoding for multiclass classification
y = to_categorical(y)

In [ ]:
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X.shape

(1000, 20)

In [ ]:
y.shape

(1000, 3)

In [ ]:
# Step 3: Define the model
model = Sequential([
    Dense(64, input_dim=X.shape[1], activation='relu'),  # Input and first hidden layer
    Dense(32, activation='relu'),                       # Second hidden layer
    Dense(y.shape[1], activation='softmax')             # Output layer for multiclass classification
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Step 4: Compile the model
# Use categorical_crossentropy as the loss for multiclass classification
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# Step 5: Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

Epoch 1/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4397 - loss: 1.0647
Epoch 2/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6197 - loss: 0.9370
Epoch 3/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6866 - loss: 0.8219
Epoch 4/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7217 - loss: 0.7085
Epoch 5/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.6213
Epoch 6/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7914 - loss: 0.5536
Epoch 7/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7944 - loss: 0.5215
Epoch 8/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8220 - loss: 0.4823
Epoch 9/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8472 - loss: 0.4501
Epoch 10/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8424 - loss: 0.4439
Epoch 11/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8727 - loss: 0.3916  
Epoch 12/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8807 - 

In [ ]:
# Step 6: Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {accuracy:.2f}")

Test Accuracy: 0.76


In [ ]:
# Step 7: Predict the class for new data
# Generate predictions for the test data
y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


In [ ]:
print("First 10 true labels:", y_true[:10])
print("First 10 predicted labels:", y_pred[:10])

First 10 true labels: [1 2 0 0 2 2 1 2 0 2]
First 10 predicted labels: [1 2 0 1 1 1 1 0 0 1]


In [ ]:
##  2b: deep forward network with two hidden layers to perform classification while predicting the probabilities of each class

In [ ]:
# Step 7: Predict probabilities of the class
# Predict the probabilities for the test data
y_prob = model.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [ ]:
# Print the predicted probabilities for the first 5 samples
print("Predicted probabilities for first 5 samples:")
print(y_prob[:5])



Predicted probabilities for first 5 samples:
[[1.7894269e-04 9.9646115e-01 3.3598617e-03]
 [3.1009644e-01 1.9343650e-03 6.8796909e-01]
 [9.9782938e-01 5.1769609e-07 2.1700819e-03]
 [2.1173763e-01 5.6319094e-01 2.2507156e-01]
 [1.4883203e-03 9.9850905e-01 2.6405685e-06]]


In [ ]:
# Convert probabilities into class predictions (optional, for comparison)
y_pred_class = (y_prob > 0.5).astype(int)
print("Predicted classes for first 5 samples:")
print(y_pred_class[:5])

Predicted classes for first 5 samples:
[[0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]]


In [ ]:
##  2c: deep forward network with two hidden layers to perform linear regression and predicting values

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Step 1: Load the dataset
data = fetch_california_housing()
X, y = data.data, data.target

# Step 2: Preprocess the data
# Scale the features to mean=0 and variance=1
scaler_X = StandardScaler()
X = scaler_X.fit_transform(X)

# Scale the target variable (y) to mean=0 and variance=1
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()  # Flatten back to a 1D array

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define the model
model = Sequential([
    Dense(64, input_dim=X.shape[1], activation='relu'),  # First hidden layer
    Dense(32, activation='relu'),                       # Second hidden layer
    Dense(1, activation='linear')                       # Output layer for regression
])

# Step 4: Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Step 5: Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

# Step 6: Evaluate the model
loss, mae = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Mean Absolute Error (MAE): {mae:.2f}")

# Step 7: Predict continuous values
y_pred = model.predict(X_test)

# Inverse scale the predictions and the true values for interpretability
y_pred_original = scaler_y.inverse_transform(y_pred)
y_test_original = scaler_y.inverse_transform(y_test.reshape(-1, 1))

# Print the first 5 predictions and their corresponding true values
print("First 5 true values:", y_test_original[:5].flatten())
print("First 5 predicted values:", y_pred_original[:5].flatten())


Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.5357 - mae: 0.5122
Epoch 2/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3004 - mae: 0.3894
Epoch 3/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2724 - mae: 0.3684
Epoch 4/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2704 - mae: 0.3608
Epoch 5/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2506 - mae: 0.3485
Epoch 6/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2789 - mae: 0.3455
Epoch 7/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2327 - mae: 0.3347
Epoch 8/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2331 - mae: 0.3347
Epoch 9/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2205 - mae: 0.3256
Epoch 10/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2166 - mae: 0.3209
Epoch 11/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2163 - mae: 0.3219
Epoch 12/50
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2175 - mae: 0.3193
Epoch 13/50
516/516 ━━━━━━━━━━━━━━━━

In [ ]:
from sklearn.datasets import make_regression
# Step 1: Generate or load the data
# Generate a synthetic dataset for regression
X, y = make_regression(
    n_samples=1000,        # Number of samples
    n_features=20,         # Number of features
    noise=0.1,             # Add some noise to make the data realistic
    random_state=42
)

In [ ]:
##  2d: evaluating feed forward deep network for regression using k fold cross validation
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


In [ ]:
# Step 1: Load the California Housing dataset
data = fetch_california_housing()
X, y = data.data, data.target

In [ ]:
# Step 2: Standardize the features and target
scaler_X = StandardScaler()
X = scaler_X.fit_transform(X)

scaler_y = StandardScaler()
y = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()  # Flatten back to 1D


In [ ]:
# Step 3: Define a function to create the model
def create_model():
    model = Sequential([
        Dense(64, activation='relu', input_dim=X.shape[1]),  # First hidden layer
        Dense(32, activation='relu'),                        # Second hidden layer
        Dense(1, activation='linear')                        # Output layer for regression
    ])
    model.compile(optimizer=Adam(), loss='mse', metrics=['mae'])
    return model

In [ ]:
# Step 4: Perform K-Fold Cross-Validation
k = 5  # Number of folds
kf = KFold(n_splits=k, shuffle=True, random_state=42)
mae_scores = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Create and train the model
    model = create_model()
    model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)  # Training in silent mode

    # Evaluate the model
    loss, mae = model.evaluate(X_test, y_test, verbose=0)
    mae_scores.append(mae)
    print(f"Fold MAE: {mae:.4f}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Fold MAE: 0.3038
Fold MAE: 0.3043
Fold MAE: 0.2939
Fold MAE: 0.2991
Fold MAE: 0.3193


In [ ]:
# Step 5: Print the final results
print("\nCross-Validation Results:")
print(f"Mean MAE: {np.mean(mae_scores):.4f}")
print(f"Standard Deviation of MAE: {np.std(mae_scores):.4f}")


Cross-Validation Results:
Mean MAE: 0.3041
Standard Deviation of MAE: 0.0085


In [ ]:
##  2e: evaluating feed forward deep network for multiclass classification using k fold cross validation
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical


In [ ]:
# Step 1: Load the Fashion MNIST dataset
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

# Combine train and test sets for cross-validation
X = np.concatenate((X_train_full, X_test), axis=0)
y = np.concatenate((y_train_full, y_test), axis=0)


29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
# Step 2: Preprocess the data
X = X / 255.0  # Normalize pixel values to range [0,1]
y = to_categorical(y, num_classes=10)  # Convert labels to one-hot encoding



In [ ]:
# Step 3: Define a function to create the model
def create_model():
    model = Sequential([
        Flatten(input_shape=(28, 28)),  # Convert 28x28 image to 1D vector
        Dense(128, activation='relu'),  # First hidden layer
        Dense(64, activation='relu'),   # Second hidden layer
        Dense(10, activation='softmax') # Output layer (10 classes)
    ])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model


In [ ]:
# Step 4: Perform K-Fold Cross-Validation
k = 5  # Number of folds
kf = KFold(n_splits=k, shuffle=True, random_state=42)
accuracy_scores = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Create and train the model
    model = create_model()
    model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)  # Training with verbose

    # Evaluate the model
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    accuracy_scores.append(accuracy)
    print(f"Fold Accuracy: {accuracy:.4f}")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.7706 - loss: 0.6515
Epoch 2/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8599 - loss: 0.3841
Epoch 3/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8725 - loss: 0.3469
Epoch 4/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8818 - loss: 0.3195
Epoch 5/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8877 - loss: 0.3015
Epoch 6/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8918 - loss: 0.2891
Epoch 7/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8985 - loss: 0.2692
Epoch 8/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9000 - loss: 0.2628
Epoch 9/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9076 - loss: 0.2471
Epoch 10/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9087 - loss: 0.2422
Fold Accuracy: 0.8911
Epoch 1/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.7739 - loss: 0.6450
Epoch 2/1

In [ ]:
# Step 5: Print the final results
print("\nCross-Validation Results:")
print(f"Mean Accuracy: {np.mean(accuracy_scores):.4f}")
print(f"Standard Deviation of Accuracy: {np.std(accuracy_scores):.4f}")