In [ ]:
#matrix multiplication and finding eigenvalues and eigenvectors using tensor flow
import tensorflow as tf

#define the 2 matrices
matrix_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [ ]:
print(matrix_a)
print(matrix_b)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [ ]:
#multiply the matrices
result = tf.matmul(matrix_a, matrix_b)

In [ ]:
import numpy as np
#diplay the result
print("Multiplication of the matrices:\n",result.numpy())

Multiplication of the matrices:
 [[19. 22.]
 [43. 50.]]


In [ ]:
#define a square matrix
matrix_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

#compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(matrix_a)

In [ ]:
print('Eigenvalues\n',eigenvalues.numpy())
print('Eigenvectors\n',eigenvectors.numpy())

Eigenvalues
 [-0.8541021  5.854102 ]
Eigenvectors
 [[-0.85065085 -0.5257311 ]
 [ 0.5257311  -0.85065085]]


In [ ]:
#define a square matrix
matrix_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

#compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(matrix_b)

In [ ]:
print('Eigenvalues\n',eigenvalues.numpy())
print('Eigenvectors\n',eigenvectors.numpy())

Eigenvalues
 [-0.6589107 13.658911 ]
Eigenvectors
 [[-0.7776661  -0.62867755]
 [ 0.62867755 -0.7776661 ]]


In [ ]:
#solving XOR problem using deep feed forward network
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
#input data for XOR
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)

#output labels for XOR
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [ ]:
#create a sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, input_dim=2, activation='relu'),#hidden layer with 4 neurons
    tf.keras.layers.Dense(1, activation='sigmoid')#output layer with 1 neuron
])

#compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#train the model
history=model.fit(x_data, y_data, epochs=500, verbose=0)

In [ ]:
#print final loss and accuracy
loss, accuracy = model.evaluate(x_data, y_data)
print(f'Final loss: {loss:.4f}')
print(f'Final accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 1.0000 - loss: 0.4740
Final loss: 0.4740
Final accuracy: 1.0000


In [ ]:
#predict ooutputs
predictions = model.predict(x_data)

#display results
print("Input:\n",x_data)
print("Predicted Output:\n", predictions)
print("Rounded Predictions:\n",np.round(predictions))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Input:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Output:
 [[0.43735823]
 [0.711875  ]
 [0.56776726]
 [0.3395527 ]]
Rounded Predictions:
 [[0.]
 [1.]
 [1.]
 [0.]]
